package jp.langstack.domain.genre;
// Generated 2021/11/06 7:59:35 by Hibernate Tools 5.3.20.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import jp.langstack.domain.card.Card;

/**
 * Genre generated by hbm2java
 */
@Entity
@Table(name="genre"
)
public class Genre  implements java.io.Serializable {


     private String id;
     private String name;
     private Set<Card> cards = new HashSet<Card>(0);

    public Genre() {
    }

	
    public Genre(String id) {
        this.id = id;
    }
    public Genre(String id, String name, Set<Card> cards) {
       this.id = id;
       this.name = name;
       this.cards = cards;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false, length=22)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    
    @Column(name="name")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="genre")
    public Set<Card> getCards() {
        return this.cards;
    }
    
    public void setCards(Set<Card> cards) {
        this.cards = cards;
    }




}


