package jp.langstack.domain.hello;
// Generated 2021/10/31 10:20:54 by Hibernate Tools 5.3.20.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Hello generated by hbm2java
 */
@Entity
@Table(name="hello"
)
public class Hello  implements java.io.Serializable {


     private String id;
     private String name;
     private Integer sortNumber;

    public Hello() {
    }

	
    public Hello(String id) {
        this.id = id;
    }
    public Hello(String id, String name, Integer sortNumber) {
       this.id = id;
       this.name = name;
       this.sortNumber = sortNumber;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false, length=22)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    
    @Column(name="name")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="sort_number")
    public Integer getSortNumber() {
        return this.sortNumber;
    }
    
    public void setSortNumber(Integer sortNumber) {
        this.sortNumber = sortNumber;
    }




}


