package jp.langstack.domain.card;
// Generated 2021/11/06 9:07:31 by Hibernate Tools 5.3.20.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import jp.langstack.domain.genre.GenreEntity;

/**
 * CardEntity generated by hbm2java
 */
@Entity
@Table(name="card"
)
public class CardEntity  implements java.io.Serializable {


     private String id;
     private GenreEntity genreEntity;
     private String title;
     private String content;
     private String imageUrl;
     private String postDate;

    public CardEntity() {
    }

	
    public CardEntity(String id, GenreEntity genreEntity) {
        this.id = id;
        this.genreEntity = genreEntity;
    }
    public CardEntity(String id, GenreEntity genreEntity, String title, String content, String imageUrl, String postDate) {
       this.id = id;
       this.genreEntity = genreEntity;
       this.title = title;
       this.content = content;
       this.imageUrl = imageUrl;
       this.postDate = postDate;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false, length=22)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="genre_id", nullable=false)
    public GenreEntity getGenreEntity() {
        return this.genreEntity;
    }
    
    public void setGenreEntity(GenreEntity genreEntity) {
        this.genreEntity = genreEntity;
    }

    
    @Column(name="title")
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    
    @Column(name="content")
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }

    
    @Column(name="image_url")
    public String getImageUrl() {
        return this.imageUrl;
    }
    
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    
    @Column(name="post_date")
    public String getPostDate() {
        return this.postDate;
    }
    
    public void setPostDate(String postDate) {
        this.postDate = postDate;
    }




}


